// <auto-generated />
using GustoGlide.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GustoGlide.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240721065401_AddProductTable")]
    partial class AddProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GustoGlide.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Pizza",
                            Description = "Баварские колбаски , соус аджика, острые колбаски чоризо , цыпленок , пикантная пепперони , моцарелла, фирменный томатный соус",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Мясная с аджикой",
                            Price = 500.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Pizza",
                            Description = "Креветки, ананасы, соус сладкий чили, сладкий перец, моцарелла, фирменный соус альфредо",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Креветки со сладким чилий",
                            Price = 550.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Pizza",
                            Description = "Моцарелла, сыры чеддер и пармезан, фирменный соус альфредо",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Сырная",
                            Price = 300.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Pizza",
                            Description = "Цыпленок, моцарелла, фирменный соус альфредо",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Двойной цыпленок",
                            Price = 420.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Pizza",
                            Description = "Ветчина, моцарелла, фирменный соус альфредо",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Ветчина и сыр",
                            Price = 420.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Pizza",
                            Description = "Острые колбаски чоризо, сладкий перец, моцарелла, фирменный томатный соус",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Чоризо фреш",
                            Price = 420.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
